# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendor_management.Vendor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendor_management.Contract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendor_management.Contract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendor_management.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendor_management.Department'),
            preserve_default=False,
        ),
    ]
