# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0002_auto_20170131_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_above',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vendor_management.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='department_below',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vendor_management.Department'),
            preserve_default=False,
        ),
    ]
