# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0003_auto_20170131_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_above',
        ),
        migrations.RemoveField(
            model_name='department',
            name='department_below',
        ),
    ]
